### ISSUE TITLE
WARNING in webpack performance recommendations

### ISSUE THREAD

**Issue by MaheshThombare** [nuvolo/sincronia#139]
npx sinc dev - sometimes unable to push changes for the same.

<img width="568" alt="Screenshot 2020-08-18 at 8 15 36 PM" src="https://user-images.githubusercontent.com/66023261/90533657-71465480-e196-11ea-959a-cdc968c6b1db.png">
<img width="570" alt="Screenshot 2020-08-18 at 8 16 38 PM" src="https://user-images.githubusercontent.com/66023261/90533691-7a372600-e196-11ea-8153-59d984533032.png">

**Comment by bbarber9** [comment]
@MaheshThombare are you building in development mode or production mode?

**Comment by MaheshThombare** [comment]
@bbarber9 development mode

**Comment by bbarber9** [comment]
Judging from the screenshots, I'm guessing that since you are in development mode it's producing a really large bundle. I think ServiceNow has limits to how big the code can be inside it's database. If you are using webpack to develop a web app and not some library, I'd recommend doing local builds for development and then trying a production build when you are ready since it should produce a smaller bundle. 

At any rate, reducing your bundle size should help with the failed pushes. Let me know if you have any more questions.

**Comment by MaheshThombare** [comment]
👍
